### ISSUE TITLE
Add configurable project detail view

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#1]
* link detail view in project list
* add detail view
* make visible fields configurable in plugin
* later some field should be visible only for some frontend user groups

**Comment by alexgunkel** [comment]
Detailansicht ist vorhanden und verlinkt.
Konfigurierbarkeit ist aktuell nicht nötig,
Lässt sich über verschiedene Templates mit TYPO3-Mitteln bewerkstelligen
