### ISSUE TITLE
** Make project editable for FE users

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#20]
* so maybe we need a field to associate a user profile that's allowed to edit the project at any time
** or just by confirming the initial e-mail address ?
* the logged in user should see a "Edit" button on his associated project page
* when project was changed we need a new approval process

**Comment by alexgunkel** [comment]
Laut Anforderungen darf jeder editieren, aber es gibt den bekannten Freigabeprozess…
