### ISSUE TITLE
Filter projects by topic

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#23]
Clicking a topic within project list should show only projects with this topic.

**Comment by alexgunkel** [comment]
feature vorhanden

**Comment by mcmulman** [comment]
Funktioniert weiterhin nicht auf TEST

**Comment by alexgunkel** [comment]
funktioniert auf test…
http://test.hypos-eastgermany.de/intern/examples/projects/project-list/?tx_projectorganizer_show_projects%5Btopic%5D=2&tx_projectorganizer_show_projects%5Baction%5D=listByTopic&tx_projectorganizer_show_projects%5Bcontroller%5D=Editor&cHash=15266fd1ffe76d1f502011508e770cbb

http://test.hypos-eastgermany.de/intern/examples/projects/project-list/?tx_projectorganizer_show_projects%5Btopic%5D=1&tx_projectorganizer_show_projects%5Baction%5D=listByTopic&tx_projectorganizer_show_projects%5Bcontroller%5D=Editor&cHash=a0def063d70946a73398e0eefb18392a

**Comment by mcmulman** [comment]
👍 works now!
