### ISSUE TITLE
*** Allow "multiple" selects in project registration form

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#25]
The select lists "topic" and "institution" must be of type "multiple".
The controller must handle the multi value.

**Comment by alexgunkel** [comment]
fluid-option: multiple="true"

**Comment by mcmulman** [comment]
Get's an error:
Uncaught TYPO3 Exception: #1297759968: Exception while property mapping at property path "institution": Property "0" was not found in target object of type "AlexGunkel\ProjectOrganizer\Domain\Model\Institution". | TYPO3\CMS\Extbase\Property\Exception thrown in file /var/www/clients/client197/web1517/web/hypos-test/_SRC/typo3_src-8.7.10/typo3/sysext/extbase/Classes/Property/PropertyMapper.php in line 127.

**Comment by alexgunkel** [comment]
update db-schema…

**Comment by alexgunkel** [comment]
halt, es ist nur der cache…

**Comment by mcmulman** [comment]
Ah sorry, didn't notice your changes... gonna try later...
