### ISSUE TITLE
Firmenverzeichnis (form, list, detail)

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#27]
Firmenverzeichnis
* Erstellungformular / Liste / Detailansicht
* Felder:

    •   Name der Institution
    •   Typ (Forschung, Großunternehmen, KMU)
    •   Hauptsitz der Institution (Stadt)
    •   Bundesland
    •   Land
    •   Themenfeld (Optionen: Strombereitstellung, Chemische Umwandlung, Transport & Speicherung, Verwertung & Vertrieb – Mehrauswahl möglich)
    •   WSK-Elemente (Liste wird nachgereicht)

**Comment by alexgunkel** [comment]
im wesentlichen vorhanden
