### ISSUE TITLE
** Expertenverzeichnis (form, list, detail)

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#28]
Expertenverzeichnis:

Anmeldeformular:
* Felder
** Details & Erfahrungen (freier Text zur Expertenbeschreibung)
** Position in der Institution
** Sitz (Anm.: dieser muss nicht unbedingt dem Hauptsitz des Unternehmens entsprechen)
** E-Mail-Adresse -> Checkbox zur öffentlichen Anzeige der E-Mail
* Weitere Elemente aus Datenbankabfrage und verknüpften Tabellen:
** Beteiligte Projekte (aus H2-Projekte) mit Verlinkung zur Projektansicht
** Veröffentlichungen (neu Tabelle in Datenbank - siehe relationales Datenbankkonzept; Abfrage der Attribute soll in View Experteneintrag erstellen durch Textinputs erfolgen)
** Weitere Experten aus der Institution (Datenbankabfrage)
** Weitere Experten bzgl. der gewählten WSK-Elemente (Datenbankabfrage nach gleichen WSK-Elementen)

List View:
* (-) Link to expert
* (-) Link to projects

Detail  View

* show all fields

**Comment by alexgunkel** [comment]
backend-funktionalität ist gegeben
