### ISSUE TITLE
* Add multiple templates for project list view  

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#29]
* so far we need two templates for project list plugin:
** list (table)
** map

**Comment by alexgunkel** [comment]
TypoScript:
{code}
plugin.tx_projectorganizer_show_projects {
    view {
        templateRootPaths.0 = EXT:project_organizer/Resources/Private/Templates/
        partialRootPaths.0 = EXT:project_organizer/Resources/Private/Partials/
        layoutRootPaths.0 = EXT:project_organizer/Resources/Private/Layouts/
    }
}
{code}

**Comment by mcmulman** [comment]
Das ist nur eine temporäre Lösung. Das muss im Plugin eingestellt werden können.
