### ISSUE TITLE
Add topic list view

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/projectorganizer#6]
* list multiple topics on project detail and list views (foreach)
* topic links should link to a project list, filtered by topic

**Comment by alexgunkel** [comment]
gibt's bereits. Sowohl auf der Listenansicht als auch in der Detailansicht ist eine Liste aller Projekte zu einem Themenfeld verlinkt

**Comment by mcmulman** [comment]
Clicking at a topic the opened list should only show projects with the chosen topic.
